### ISSUE TITLE
DevEnv Setup

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#1]
## User story
As a **developer**, 
I want to have a clean basic development enviroment which is completely deployed
so I can completely focus on programming the components for my App

## Notes / Links / Further Description
- For orientation
https://github.com/lmachens/full-stack-template
https://github.com/slawoe/fullstack-template

## ToDos
- [x] Setup repo in GitHub with ReadMe, MIT License and Node gitignore
- [x] Clone locally
- [x] Add package.json
- [x] Add server.js and server starting script to package.json
- [x] Setup project on Heroku and add read port from enviroment for the deployment
- [x] Add prettier
- [x] Add ES-Lint
- [x] Add eslint-config-prettier
- [x] Add lint-staged and husky
- [x] Install Create React App to Client-Level
- [x] Write eslintignore and the scripts for linting
- [x] Add build-scripts to TOP-Level
- [x] Add storybook and dependecies
- [x] Build storybook
- [x] Check if deployment is working
- [x] Add Json server and paths
- [x] Add ReactRouter
- [x] Emotion core and styled
- [x] Add ReactQuery
- [x] Add propTypes
- [x] Add dotenv
- [x] Add node fetch
