### ISSUE TITLE
Design setup

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#17]
## UserStory

As a **developer**,
I want to have a clear Design in Adobe XD for my App,
so I can completely concetrate afterwards on coding the components.

## ToDos

- [x] Add new project on Adobe XD
- [x] Setup color scheme
- [x] Setup fonts
- [x] Analyze userflow
- [x] Start designing components
- [x] Add together to pages
- [x] Ask for review
- [x] Adapt changes to own design
