### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#18]
## User story

As a **developer**,
I want to have a working prototype of my App on Adobe XD,
so I can understand the routes between my Pages in a better way and also see upcoming logic failures or problems before starting to code the App.

## ToDos

- [x] Finish design
- [x] Start link the components with actions
- [x] Check if there are logical mistakes
- [x] Await for reviews
