### ISSUE TITLE
Navigation/Menu

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#22]
## User story

As a **user**,
I want to have a simple self-explaining an inuitve menu,
so I can navigate easy through the App and find the things I'm searching for

## ToDos

- [x] Decide for a layout (footer navigation, header/drawer navigation or both)
- [x] Write footer component
- [x] Search for the needed icons and import them to assets
- [x] Import necessary colors and fonts to GlobalStyles
- [x] Decide for space between the components and size of the menu if header/drawer menu
