### ISSUE TITLE
Errorpage

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#23]
## User story

As a **user**,
I want to see an error message if something has went wrong,
so I know what mistake I've made or if it is a problem with the App itself, so I can user-behavior to avoid these mistakes again.

## ToDos

- [x] Set Error basic screen
- [x] Add ErrorMessages in JavaScript to the Screen
- [x] Add different Error-Messages if error is caused by user, maybe wrong Password
