### ISSUE TITLE
AppOnboarding

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#24]
## User story

As a **user**,
I want to have a short and simple Onboarding to the App
so I know what I can do and what I can do to use the App in an efficient way

## Notes / Links / Further Description
See design in Adobe XD

## ToDos

- [x] Program the Onboarding page
- [x] Add the routes for the links
- [x] Add the texts for Onboarding
