### ISSUE TITLE
Architecture of DataBase/API

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#25]
## User story

As a **developer**,
I want to set up a clear database structure with all needed and possible information,
so that I can test with a RESTFUL API on the json-server before I set it up on MongoDB.

## ToDos

- [x] Write down all possible information you want to store in the database
- [x] Think about how this data can be used by other parties for logical structure
- [x] Add categories for data
- [x] Add API routes for GET
- [x] Add API routes for POST
- [x] Add API routes for DELETE
- [x] Add API routes for PATCH
