### ISSUE TITLE
Implementation of MongoDB

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#26]
## User story

As a **developer**,
I want to have clear routes and models to my database, so that all information from client is landing in the database

## ToDos

- [x] Add routes for diary
- [x] Add routes for doctors
- [x] Add routes for medics
- [x] Add routes for user
- [x] Add models for diary
- [x] Add models for doctors
- [x] Add models for medics
- [x] Add models for user
- [x] Update server.js with middlewares
- [x] Add sorting
- [x] Test
