### ISSUE TITLE
SignUpProcess

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#28]
## User story

As a **user**,
I want to have the possibility to sign up for the App If I have no account, so I can use it and now that my data is safe and linked to my person.

## ToDos

- [x] Set up form
- [x] Set up the routes
- [x] Test it with postman
