### ISSUE TITLE
WelcomeScreen

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#29]
## User story

As a **user** I would like to have a starting point in the app after login, from where I can navigate to the desired areas to have a better overview

## ToDos

- [x] Think about the informations that have to be shown 
- [x] Write Welcome.js
- [x] Implement in routing
