### ISSUE TITLE
CallButton

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#30]
## User story

As a **user**,
I want to have as button which makes it possible to call a number for psychological help any time,
so I can talk to anybody about my problems if nobody is here to talk to.

## ToDos

- [x] Write the button
- [x] Add icon
- [x] Give it a call function with href ti Telefonseelsorge
- [x] Write storybook story for the button
