### ISSUE TITLE
Set up Routing

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#41]
## User story

As a **developer** I would like to offer my user a comprehensible and clearly functioning navigation so that he can easily navigate between the individual pages.

## ToDos

- [x] Set up Routing in App.js -> LoginScreen, Home, Registration
- [x] Set up Routing -> in Registration through the form pages to Home
- [x] Set up Routing in Home to all other pages via Switch
- [X] Test all paths
