### ISSUE TITLE
About

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#43]
## User story

As a **user** I would like to know more about the app, so that I can get a better picture

## Notes / Links / Further Description
Short description of the page

## ToDos

- [x] Styling of the container
- [x] Write the text for About.js
- [x] Write About.js
- [x] Implement in Routing
