### ISSUE TITLE
QuestionnaireForm

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#46]
## User story

As a **user** I would like to have the possibility to write a daily entry in the diary, so that I can view and evaluate it afterwards.

## Notes / Links / Further Description
Try to use the RegistrationForm and change the files you need

## ToDos

- [x] Decide which questions are asked
- [x] Decide the Icons
- [x] Code extra Input Components for textarea and slider pages
- [x] Write the questionnaire pages
- [x] Route correctly
- [x] Arrange a review editible site
- [x] Create Sumbit and Sumbit page
