### ISSUE TITLE
Collapsible and diary

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#48]
## User story

As a **user** I would like to have my diary entries displayed in a list and, if desired, have more details displayed so that I can better deal with my days, but still not lose the overview with lots of information.

## Notes / Links / Further Description
Check out collapsible tutorials

## ToDos

- [x]Create collapsible component
- [x]Add needed informations
- [x]Setup page with mockup data to map through
- [x]Create Storybook story
- [x]Change paths to Diary
