### ISSUE TITLE
Edit and Delete buttons

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#51]
## User story

As a **user**, I would like to be able to edit or delete posts so that I can keep my entries clean

## ToDos

- [x]Design edit and delete button
- [x]Code as component
- [x]Give them functionality
