### ISSUE TITLE
Medics and Doctors page

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#52]
## User story

As a user, I would like to have an overview of my medications and doctors so that I can communicate with my doctor better and do not lose track

## ToDos

- [x]Design the medics page
- []Code wrapper component for add page
- []Code Medics list item
- []Code doctors list item
- []Code Add pages
- []Code edit and delete pages
