### ISSUE TITLE
Doctors

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#56]
## User story

As a **user** I would like,
add my doctors, show them to me and edit or delete them to keep a better overview of them and always be up to date.

## ToDos

- [x] Set fetches with routes
- [x] set handleSubmits
- [x] set logic forms
- [x] Add PATCH and DELETE functionality
- [x] Fetch single doctor
- [x] test
