### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by slawoe** [slawoe/moodster#64]
## User story

As a **user**, I want to be able to search my entries to get to important data faster and see only what is relevant for me

## ToDos

- [x] Add search component
- [x] Add functionality to search component
- [x] Filter results in medics, doctors and diaries
- [x] Add search function to medics, doctors and diaries
